"""Optional live LLM reasoning for AGENT_REPLAN / AGENT_AUDIT.

Off by default (CONFIG["AGENT_LLM_ENABLED"] — see policies.example.yaml)
so task creation stays fast, deterministic and network-free unless you
explicitly opt in. When enabled AND a Groq API key is available, the
agent's message is generated by a real Groq-hosted model instead of the
built-in computed wording; on ANY failure (feature off, no key, network
error, timeout, bad response) this quietly returns None and the caller
keeps using its own computed message — a live model is a narration layer
over real computed data here, never a hard dependency, and never the
thing that decides whether a task passes or fails.

Reuses the same GROQ_API_KEY the promptfoo Groq suite already uses (see
evals/README.md and evals/.env) — no separate setup needed.
"""
from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Optional

from .models import CONFIG

GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "openai/gpt-oss-20b"
TIMEOUT_SECONDS = 6
MAX_TOKENS = 200

_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_ENV_FALLBACK_PATH = os.path.join(_BASE_DIR, "evals", ".env")


def find_api_key() -> Optional[str]:
    key = os.environ.get("GROQ_API_KEY")
    if key:
        return key
    # Fall back to evals/.env — gitignored, holds the same key the
    # promptfoo Groq suite reads (see evals/generate_tests_groq.py).
    try:
        with open(_ENV_FALLBACK_PATH, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line.startswith("GROQ_API_KEY="):
                    value = line.split("=", 1)[1].strip().strip('"').strip("'")
                    return value or None
    except OSError:
        pass
    return None


def enabled() -> bool:
    return bool(CONFIG.get("AGENT_LLM_ENABLED")) and find_api_key() is not None


def narrate(prompt: str, system: Optional[str] = None) -> Optional[str]:
    """Ask a real Groq-hosted model to phrase `prompt` in one or two
    short sentences. Returns None (never raises) if the feature is
    disabled, no key is configured, or the call fails for any reason —
    callers must always have a computed fallback ready."""
    if not CONFIG.get("AGENT_LLM_ENABLED"):
        return None
    api_key = find_api_key()
    if not api_key:
        return None

    body = json.dumps({
        "model": GROQ_MODEL,
        "messages": [
            {
                "role": "system",
                "content": system or (
                    "You are a warehouse operations AI assistant. Reply in one or "
                    "two short, plain sentences. No preamble, no markdown."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "max_tokens": MAX_TOKENS,
        "temperature": 0.3,
    }).encode("utf-8")
    request = urllib.request.Request(
        GROQ_URL,
        data=body,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
            # Groq's API sits behind Cloudflare, which blocks the default
            # urllib User-Agent outright (HTTP 403, Cloudflare error
            # 1010) — a normal-looking one is enough to pass.
            "User-Agent": "Mozilla/5.0 (compatible; warehouse-digital-twin/1.0)",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:
            payload = json.loads(response.read().decode("utf-8"))
        text = payload["choices"][0]["message"]["content"]
        return text.strip() or None
    except (urllib.error.URLError, TimeoutError, KeyError, IndexError, ValueError, OSError):
        return None
